"""
NoovaStack VAPT Platform - Scan Profiles Configuration
"""
from database.models import ScanProfile

DEFAULT_SCAN_PROFILES = [
    {
        "id": "quick_web_black_box",
        "name": "Quick Website Scan",
        "category": "website",
        "depth": "quick",
        "assessment_modes": ["black_box"],
        "enabled_modules": [
            "passive_asset_discovery",
            "tcp_port_scan",
            "service_detection",
            "http_probe",
            "httpx_probe",
            "whatweb_fingerprint",
            "tls_check",
            "sslscan",
            "security_headers",
            "safe_nuclei_templates",
            "nikto_scan",
            "wapiti_scan",
            "cve_enrichment",
        ],
        "risk_level": "low",
        "approval_required": False,
        "senior_approval_required": False,
    },
    {
        "id": "standard_web_black_box",
        "name": "Standard Website Scan",
        "category": "website",
        "depth": "standard",
        "assessment_modes": ["black_box"],
        "enabled_modules": [
            "asset_discovery",
            "web_crawl",
            "owasp_top_10",
            "security_headers",
            "tls_check",
            "technology_detection",
            "whatweb_fingerprint",
            "httpx_probe",
            "nuclei_templates",
            "nikto_scan",
            "wapiti_scan",
            "testssl_scan",
            "evidence_collection",
            "ai_analysis",
            "cve_enrichment",
            "report_generation",
        ],
        "risk_level": "medium",
        "approval_required": False,
        "senior_approval_required": False,
    },
    {
        "id": "standard_web_gray_box",
        "name": "Standard Authenticated Web Scan",
        "category": "website",
        "depth": "standard",
        "assessment_modes": ["gray_box"],
        "enabled_modules": [
            "asset_discovery",
            "authenticated_crawl",
            "owasp_top_10",
            "wapiti_scan",
            "nuclei_templates",
            "nikto_scan",
            "session_testing",
            "authorization_testing",
            "evidence_collection",
            "ai_analysis",
            "cve_enrichment",
            "report_generation",
        ],
        "risk_level": "medium",
        "approval_required": True,
        "senior_approval_required": False,
    },
    {
        "id": "deep_web_gray_box",
        "name": "Deep Authenticated Web Scan",
        "category": "website",
        "depth": "deep",
        "assessment_modes": ["gray_box"],
        "enabled_modules": [
            "deep_crawl",
            "authenticated_scanning",
            "owasp_top_10",
            "wapiti_scan",
            "nuclei_templates",
            "nikto_scan",
            "dalfox_xss",
            "sqlmap_check",
            "business_logic_testing",
            "authorization_comparison",
            "file_upload_validation",
            "parameter_discovery",
            "controlled_validation",
            "evidence_collection",
            "ai_analysis",
            "cve_enrichment",
            "report_generation",
        ],
        "risk_level": "high",
        "approval_required": True,
        "senior_approval_required": True,
    },
    {
        "id": "white_box_complete",
        "name": "White-Box Complete Assessment",
        "category": "combined_vapt",
        "depth": "deep",
        "assessment_modes": ["white_box"],
        "enabled_modules": [
            "repository_scan",
            "semgrep_sast",
            "bandit_sast",
            "dependency_scan",
            "pip_audit",
            "secret_scan",
            "container_scan",
            "trivy_scan",
            "grype_scan",
            "authenticated_web_scan",
            "api_scan",
            "finding_correlation",
            "cve_enrichment",
            "evidence_collection",
            "report_generation",
        ],
        "risk_level": "high",
        "approval_required": True,
        "senior_approval_required": True,
    },
    {
        "id": "standard_api_black_box",
        "name": "Standard API Scan",
        "category": "api_security",
        "depth": "standard",
        "assessment_modes": ["black_box", "gray_box"],
        "enabled_modules": [
            "api_discovery",
            "owasp_api_top_10",
            "nuclei_templates",
            "httpx_probe",
            "authentication_testing",
            "rate_limiting_check",
            "input_validation",
            "token_handling",
            "error_leakage",
            "cve_enrichment",
            "evidence_collection",
            "report_generation",
        ],
        "risk_level": "medium",
        "approval_required": False,
        "senior_approval_required": False,
    },
    {
        "id": "standard_network",
        "name": "Standard Network Scan",
        "category": "network",
        "depth": "standard",
        "assessment_modes": ["black_box"],
        "enabled_modules": [
            "host_discovery",
            "naabu_scan",
            "tcp_port_scan",
            "service_detection",
            "version_detection",
            "tls_services",
            "sslscan",
            "testssl_scan",
            "known_vulnerabilities",
            "cve_enrichment",
            "report_generation",
        ],
        "risk_level": "medium",
        "approval_required": True,
        "senior_approval_required": False,
    },
    {
        "id": "standard_repository",
        "name": "Standard Repository Scan",
        "category": "repository",
        "depth": "standard",
        "assessment_modes": ["white_box"],
        "enabled_modules": [
            "sast_scan",
            "semgrep_sast",
            "bandit_sast",
            "secret_detection",
            "dependency_scan",
            "pip_audit",
            "container_scan",
            "trivy_scan",
            "grype_scan",
            "iac_scan",
            "cve_enrichment",
            "report_generation",
        ],
        "risk_level": "low",
        "approval_required": False,
        "senior_approval_required": False,
    },
    {
        "id": "quick_attack_surface",
        "name": "Quick Attack Surface Scan",
        "category": "external_attack_surface",
        "depth": "quick",
        "assessment_modes": ["black_box"],
        "enabled_modules": [
            "passive_subdomain_enum",
            "dns_discovery",
            "certificate_transparency",
            "http_probe",
            "httpx_probe",
            "technology_detection",
            "whatweb_fingerprint",
            "nuclei_templates",
            "cve_enrichment",
            "report_generation",
        ],
        "risk_level": "low",
        "approval_required": False,
        "senior_approval_required": False,
    },
]
