'use client';

import Link from 'next/link';
import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { Activity, AlertTriangle, Bot, CheckCircle2, Clock, FileText, Pause, Play, ShieldCheck, Square, XCircle } from 'lucide-react';
import { toast } from 'sonner';
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from 'recharts';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader } from '@/components/ui/card';
import { ProgressBar } from '@/components/ui/progress';
import { StatusBadge, SeverityBadge } from '@/components/ui/badge';
import { formatDate, titleCase } from '@/lib/utils';
import { api } from '@/lib/api-client';
import { useAuth } from '@/hooks/use-auth';
import type { Asset, Scan, ScanEvent, ScanEvidencePayload, ScanModule, ScanProcessPayload, ScanResultsPayload, ScanSafetyState, ScanValidationResult } from '@/types';

export const workflowSteps = ['Scan Details', 'Scan Configuration', 'Scope and Permissions', 'Review and Approvals', 'Launch Scan'];

export const scanTypes = [
  ['vulnerability_scan', 'Vulnerability Scan', 'Run a general safe scan for common weaknesses across approved targets.'],
  ['website', 'Web Application', 'Assess web applications for common security weaknesses.'],
  ['api_security', 'API', 'Assess REST, GraphQL, OpenAPI, and Postman-based APIs.'],
  ['network', 'Network', 'Discover approved hosts, ports, and exposed services.'],
  ['container', 'Container', 'Check container images, packages, dependencies, and known CVEs.'],
] as const;

export const modulesByType: Record<string, string[]> = {
  vulnerability_scan: ['Scope Validation', 'Asset Verification', 'HTTP Probing', 'Port Discovery', 'Security Headers Check', 'Known Vulnerability Correlation', 'CVE Enrichment', 'Evidence Collection', 'Finding Validation', 'Report Draft'],
  website: ['Scope Validation', 'HTTP Probing and Crawling', 'TLS/SSL Analysis', 'Security Headers Check', 'OWASP Web Checks', 'Technology Detection', 'Sensitive Information Disclosure', 'Evidence Collection', 'Finding Validation', 'AI Explanation', 'Report Draft'],
  api_security: ['API Discovery', 'Authentication Testing', 'Authorization Checks', 'Rate Limiting Check', 'Input Validation', 'Token Handling', 'Evidence Collection', 'API Security Agent Analysis', 'Report Draft'],
  network: ['Host Discovery', 'Port Scan', 'Service Detection', 'Version Detection', 'TLS Services', 'Known Vulnerability Correlation', 'CVE Enrichment', 'Report Draft'],
  container: ['Container Image Scan', 'Package Inventory', 'Dependency Audit', 'CVE Enrichment', 'Misconfiguration Check', 'Evidence Collection', 'Report Draft'],
};

export function ScanWorkflowHeader({ step }: { step: number }) {
  return <div className="grid gap-2 md:grid-cols-5">{workflowSteps.map((label, index) => <div key={label} className={`rounded-xl border p-3 text-xs font-semibold ${index === step ? 'border-[#E51C2A] bg-red-50 text-[#B91C1C]' : index < step ? 'border-green-200 bg-green-50 text-[#16A34A]' : 'border-[#E2E8F0] bg-white text-[#64748B]'}`}>{index + 1}. {label}</div>)}</div>;
}

export function TargetSelection({ assets, selectedIds, onChange }: { assets: Asset[]; selectedIds: string[]; onChange: (ids: string[]) => void }) {
  const [query, setQuery] = useState('');
  const [type, setType] = useState('All');
  const [status, setStatus] = useState('All');
  const filtered = assets.filter((asset) => `${asset.value} ${asset.name ?? ''}`.toLowerCase().includes(query.toLowerCase()) && (type === 'All' || asset.asset_type === type) && (status === 'All' || asset.approval_status === status));
  const selectable = filtered.filter(isSelectableAsset);
  return <Card><CardHeader><h2 className="font-semibold text-[#0F172A]">Target Selection</h2><p className="text-sm text-[#64748B]">Choose the authorized assets to scan.</p></CardHeader><CardContent><div className="mb-4 flex flex-wrap gap-2 text-sm"><Tab label="Assets" active /><Tab label="Asset Groups" /><Tab label="Domains" /><Tab label="IP Addresses" /><Tab label="Import from File" /></div><div className="mb-4 grid gap-3 md:grid-cols-[1fr_180px_180px_auto_auto]"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search assets" className="rounded-lg border border-[#E2E8F0] px-3 py-2 text-sm" /><select value={type} onChange={(event) => setType(event.target.value)} className="rounded-lg border border-[#E2E8F0] px-3 py-2 text-sm"><option>All</option>{Array.from(new Set(assets.map((asset) => asset.asset_type))).map((item) => <option key={item}>{item}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-lg border border-[#E2E8F0] px-3 py-2 text-sm"><option>All</option><option>approved</option><option>pending</option><option>rejected</option></select><Button variant="secondary" onClick={() => onChange(selectable.map((asset) => asset.id))}>Select all</Button><Button variant="outline" onClick={() => onChange([])}>Clear</Button></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="text-[#64748B]"><tr>{['Selection', 'Asset', 'Type', 'Status', 'IP or URL', 'Actions'].map((header) => <th key={header} className="py-2">{header}</th>)}</tr></thead><tbody>{filtered.map((asset) => { const disabledReason = disabledAssetReason(asset); const disabled = Boolean(disabledReason); return <tr key={asset.id} className="border-t border-[#E2E8F0]"><td className="py-3"><input type="checkbox" checked={selectedIds.includes(asset.id)} disabled={disabled} title={disabledReason} onChange={(event) => onChange(event.target.checked ? [...selectedIds, asset.id] : selectedIds.filter((id) => id !== asset.id))} /></td><td><p className="font-semibold text-[#0F172A]">{asset.name ?? asset.value}</p>{disabledReason ? <p className="text-xs text-amber-700">{disabledReason}</p> : null}</td><td>{titleCase(asset.asset_type)}</td><td><StatusBadge value={asset.approval_status === 'approved' && asset.scope_status === 'in_scope' ? 'approved' : asset.approval_status} /></td><td>{asset.value}</td><td><Link href={`/assets/${asset.id}`} className="text-[#2563EB]">Details</Link></td></tr>; })}</tbody></table></div><div className="mt-4 flex flex-wrap gap-2"><Link href="/assets"><Button variant="outline">Add assets</Button></Link><Link href="/assets/discovery"><Button variant="outline">Import scope file</Button></Link></div></CardContent></Card>;
}

export function ScanTypeSelector({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <SelectorGrid items={scanTypes.map(([id, title, text]) => ({ id, title, text }))} value={value} onChange={onChange} />; }
export function AssessmentModeSelector({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <SelectorGrid columns="md:grid-cols-3" items={[{ id: 'black_box', title: 'Black Box', text: 'No credentials or internal knowledge. Tests the system from an external perspective.' }, { id: 'gray_box', title: 'Gray Box', text: 'Limited authorized access. May include test accounts, API documentation, or selected internal details.' }, { id: 'white_box', title: 'White Box', text: 'Full authorized access. May include source code, architecture information, test accounts, and configuration.' }]} value={value} onChange={onChange} />; }
export function ScanDepthSelector({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <SelectorGrid columns="md:grid-cols-4" items={[{ id: 'quick', title: 'Quick', text: 'Light coverage for frequent checks and development validation.' }, { id: 'standard', title: 'Standard', text: 'Balanced coverage recommended for most assessments.' }, { id: 'deep', title: 'Deep', text: 'Comprehensive testing that may require additional approval.' }, { id: 'custom', title: 'Custom', text: 'Select individual modules and advanced testing options.' }]} value={value} onChange={onChange} />; }

export function AuthenticationProfileSelector({ value, onChange }: { value: string; onChange: (value: string) => void }) { const profiles = ['None', 'Default Auth Profile', 'Customer Test User', 'Administrator Test User', 'API OAuth Profile', 'OpenID Connect Profile', 'Postman Environment', 'Browser Session Profile', 'Multiple Test-User Roles']; return <Card><CardHeader><h2 className="font-semibold">Authentication Profile</h2><p className="text-sm text-[#64748B]">Use credential references only. Secret values are never displayed after saving.</p></CardHeader><CardContent><select value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded-lg border border-[#E2E8F0] px-3 py-2 text-sm">{profiles.map((profile) => <option key={profile} value={profile}>{profile}</option>)}</select></CardContent></Card>; }

export function ScanSummaryPanel({ project, engagement, authorization, scanType, mode, depth, assets, schedule, validation }: { project?: string; engagement?: string; authorization?: string; scanType: string; mode: string; depth: string; assets: number; schedule: string; validation?: ScanValidationResult }) { return <Card className="sticky top-20"><CardHeader><h2 className="font-semibold text-[#0F172A]">Scan Summary</h2></CardHeader><CardContent className="space-y-3 text-sm"><Info label="Project" value={project ?? 'Select project'} /><Info label="Engagement" value={engagement ?? 'Not linked'} /><Info label="Authorization" value={authorization ?? 'Assets and safety controls'} /><Info label="Scan Type" value={titleCase(scanType)} /><Info label="Access Mode" value={titleCase(mode)} /><Info label="Scan Depth" value={titleCase(depth)} /><Info label="Selected assets" value={`${assets} selected`} /><Info label="Estimated duration" value={validation?.estimated_duration ?? (depth === 'deep' ? '4h-8h' : depth === 'quick' ? '15m-45m' : '2h-3h')} /><Info label="Approval required" value={validation?.approval_required ? 'Yes' : depth === 'deep' || mode !== 'black_box' ? 'Likely' : 'No'} /><Info label="Schedule" value={schedule} /></CardContent></Card>; }

export function SelectedModulesPanel({ scanType, advanced = false }: { scanType: string; advanced?: boolean }) { const modules = modulesByType[scanType] ?? modulesByType.website; return <Card><CardHeader><h2 className="font-semibold">Selected Modules</h2><p className="text-sm text-[#64748B]">Modules update from scan type, depth, mode, and safety policy.</p></CardHeader><CardContent><div className="grid gap-2">{modules.map((module) => <div key={module} className="rounded-xl border border-[#E2E8F0] bg-white p-3 text-sm"><p className="font-semibold text-[#0F172A]">{module}</p>{advanced ? <p className="mt-1 text-xs text-[#64748B]">Controlled adapter, scope-locked, output redacted.</p> : null}</div>)}</div></CardContent></Card>; }

export function SafetyConstraintsPanel() { const controls = ['DoS Protection', 'Rate Limiting', 'Scope Enforcement', 'Out-of-Scope Blocking', 'Testing Window Validation', 'Kill Switch', 'Approval Gate', 'Evidence Redaction']; const blocked = ['Denial of service', 'Password brute forcing', 'Credential theft', 'Malware execution', 'Persistent access', 'Data exfiltration', 'Production data modification', 'Unauthorized pivoting', 'Out-of-scope testing']; return <Card><CardHeader><h2 className="font-semibold">Safety and Constraints</h2></CardHeader><CardContent><div className="grid gap-2 sm:grid-cols-2">{controls.map((control) => <div key={control} className="flex items-center justify-between rounded-xl border border-[#E2E8F0] p-3 text-sm"><span>{control}</span><StatusBadge value={control === 'Approval Gate' ? 'ready' : 'enabled'} /></div>)}</div><div className="mt-4 rounded-xl border border-red-100 bg-red-50 p-3 text-sm text-red-800"><p className="font-semibold">Always blocked</p><p className="mt-1">{blocked.join(', ')}.</p></div><Link href="/engagements" className="mt-4 inline-flex text-sm font-semibold text-[#2563EB]">View Rules of Engagement</Link></CardContent></Card>; }

export function ScanContextHeader({ scan }: { scan?: Scan }) { return <div className="rounded-3xl bg-[#071B33] p-6 text-white"><div className="grid gap-4 md:grid-cols-3 xl:grid-cols-5"><InfoDark label="Scan ID" value={scan?.id ?? 'Loading'} /><InfoDark label="Project" value={scan?.project_id ?? 'Unknown'} href={scan?.project_id ? `/projects/${scan.project_id}` : undefined} /><InfoDark label="Engagement" value={scan?.engagement_id ?? 'Not linked'} /><InfoDark label="Scan Type" value={titleCase(scan?.scan_category)} /><InfoDark label="Status" value={titleCase(scan?.status)} /><InfoDark label="Access Mode" value={titleCase(scan?.assessment_mode)} /><InfoDark label="Scan Depth" value={titleCase(scan?.scan_depth)} /><InfoDark label="Started Time" value={formatDate(scan?.started_at)} /><InfoDark label="Estimated Completion" value="Operational estimate" /><InfoDark label="Authorization" value="Authorized scope required" /></div></div>; }

export function OverallProgress({ progress, status }: { progress: number; status?: string }) { return <Card><CardHeader><div className="flex items-center justify-between"><h2 className="font-semibold">Overall Progress</h2><StatusBadge value={status ?? 'pending'} /></div></CardHeader><CardContent><ProgressBar value={progress} label={`Overall Progress: ${progress}%`} /><div className="mt-4 grid gap-3 text-sm md:grid-cols-3"><Info label="Elapsed Time" value="Calculated by worker" /><Info label="Remaining Time" value="Estimate only" /><Info label="Current Phase" value={progress < 20 ? 'Setup' : progress < 45 ? 'Discovery' : progress < 75 ? 'Scanning' : progress < 95 ? 'Analysis' : 'Reporting'} /></div></CardContent></Card>; }

export function HighLevelScanSteps({ status, progress }: { status?: string; progress: number }) { const steps = ['Setup', 'Discovery', 'Scanning', 'Analysis', 'Reporting']; return <Card><CardHeader><h2 className="font-semibold">High-Level Scan Steps</h2></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-5">{steps.map((step, index) => { const threshold = (index + 1) * 20; const state = status === 'failed' ? 'Failed' : status === 'blocked' ? 'Blocked' : progress >= threshold ? 'Completed' : progress >= threshold - 20 ? 'Running' : 'Pending'; return <div key={step} className="rounded-xl border border-[#E2E8F0] p-3"><p className="font-semibold text-[#0F172A]">{step}</p><p className="mt-1 text-sm text-[#64748B]">{state}</p></div>; })}</div></CardContent></Card>; }

export function ModuleTimeline({ modules }: { modules: ScanModule[] }) { return <Card><CardHeader><h2 className="font-semibold">Module Timeline</h2></CardHeader><CardContent><div className="space-y-3">{modules.map((module, index) => <div key={module.id ?? module.module_name ?? index} className="rounded-2xl border border-[#E2E8F0] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold text-[#64748B]">{module.number ?? index + 1}</p><h3 className="font-semibold text-[#0F172A]">{module.name ?? module.module_name}</h3><p className="mt-1 text-sm text-[#64748B]">{module.description ?? 'Running approved module tasks.'}</p></div><StatusBadge value={module.status} /></div><div className="mt-3"><ProgressBar value={module.progress_percent ?? module.progress ?? 0} /></div><div className="mt-3 grid gap-2 text-xs text-[#64748B] md:grid-cols-4"><span>Started: {formatDate(module.started_at)}</span><span>Ended: {formatDate(module.completed_at)}</span><span>Outputs: {module.output_count ?? 0}</span><span>Warnings: {module.warning_count ?? 0}</span></div></div>)}</div></CardContent></Card>; }

export function LiveEventsFeed({ events }: { events: ScanEvent[] }) { return <Card><CardHeader><h2 className="font-semibold">Live Events Feed</h2></CardHeader><CardContent><div className="space-y-3">{events.length ? events.map((event) => <div key={event.id} className="rounded-xl border border-[#E2E8F0] p-3 text-sm"><div className="flex items-center justify-between gap-3"><p className="font-semibold text-[#0F172A]">{event.summary}</p><StatusBadge value={event.severity} /></div><p className="mt-1 text-xs text-[#64748B]">{formatDate(event.created_at)} · {event.agent_id ?? event.worker_id ?? event.event_type}</p></div>) : <p className="text-sm text-[#64748B]">No events recorded yet.</p>}</div></CardContent></Card>; }

export function ScanSafetyPanel({ safety }: { safety?: ScanSafetyState }) { const rows = safety ? Object.entries(safety).filter(([key]) => key !== 'last_checked_at') : []; return <Card><CardHeader><h2 className="font-semibold">Safety Controls</h2></CardHeader><CardContent className="space-y-2">{rows.map(([key, value]) => <div key={key} className="flex items-center justify-between rounded-xl border border-[#E2E8F0] p-3 text-sm"><span>{titleCase(key)}</span><StatusBadge value={String(value)} /></div>)}</CardContent></Card>; }

export function CandidateFindingsSummary({ counts }: { counts: Record<string, number> }) { return <Card><CardHeader><h2 className="font-semibold">Candidate Findings Detected</h2></CardHeader><CardContent><div className="grid grid-cols-2 gap-3">{['critical', 'high', 'medium', 'low', 'informational'].map((severity) => <div key={severity} className="rounded-xl border border-[#E2E8F0] p-3"><SeverityBadge value={severity} /><p className="mt-2 text-2xl font-bold text-[#0F172A]">{counts[severity] ?? 0}</p></div>)}</div></CardContent></Card>; }

export function EvidenceSummary({ evidence }: { evidence?: ScanEvidencePayload }) { const counts = evidence?.counts ?? {}; const rows = ['Screenshots', 'HTTP Requests', 'HTTP Responses', 'Tool Outputs', 'Code Excerpts', 'Files']; return <Card><CardHeader><h2 className="font-semibold">Evidence Captured</h2></CardHeader><CardContent><div className="grid grid-cols-2 gap-3">{rows.map((row) => <Link key={row} href="/findings" className="rounded-xl border border-[#E2E8F0] p-3"><p className="text-sm text-[#64748B]">{row}</p><p className="mt-1 text-2xl font-bold text-[#0F172A]">{counts[row] ?? 0}</p></Link>)}</div><p className="mt-3 text-xs text-[#64748B]">Evidence is redacted before normal users can view it.</p></CardContent></Card>; }

export function ScanProcessOverview({ process }: { process?: ScanProcessPayload }) { return <Card><CardHeader><h2 className="font-semibold">Process Overview</h2></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{(process?.stages ?? []).map((stage) => <div key={stage.name} className="rounded-2xl border border-[#E2E8F0] p-4"><StatusBadge value={stage.status} /><h3 className="mt-3 font-semibold text-[#0F172A]">{stage.name}</h3><p className="mt-2 text-sm text-[#64748B]">{stage.description}</p><p className="mt-3 text-xs text-[#64748B]">Outputs: {stage.output_count} · Warnings: {stage.warning_count}</p></div>)}</div></CardContent></Card>; }

export function EvidencePipeline({ process }: { process?: ScanProcessPayload }) { return <Card><CardHeader><h2 className="font-semibold">Evidence Pipeline</h2></CardHeader><CardContent><div className="space-y-3">{(process?.evidence_pipeline ?? []).map((stage, index) => <div key={stage.stage} className="rounded-2xl border border-[#E2E8F0] p-4"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#071B33] text-sm font-bold text-white">{index + 1}</span><div><h3 className="font-semibold text-[#0F172A]">{stage.stage}</h3><p className="text-xs text-[#64748B]">{stage.agent ?? 'Platform workflow'}</p></div><StatusBadge value={stage.status} /></div><p className="mt-3 text-sm text-[#64748B]">Items: {stage.item_count} · Errors: {stage.errors} · Rejected: {stage.rejected_count} · Time: {stage.processing_time}</p></div>)}</div></CardContent></Card>; }

export function FindingsQueue({ results }: { results?: ScanResultsPayload }) { return <Card><CardHeader><h2 className="font-semibold">Findings Queue</h2></CardHeader><CardContent><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="text-[#64748B]"><tr>{['Finding ID', 'Title', 'Severity', 'Asset', 'Status', 'Evidence', 'Actions'].map((h) => <th key={h} className="py-2">{h}</th>)}</tr></thead><tbody>{(results?.findings ?? []).map((finding) => <tr key={finding.id} className="border-t border-[#E2E8F0]"><td className="py-3 text-xs">{finding.id.slice(0, 8)}</td><td className="font-semibold text-[#0F172A]">{finding.title}</td><td><SeverityBadge value={finding.severity} /></td><td>{finding.asset_id?.slice(0, 8) ?? 'n/a'}</td><td><StatusBadge value={finding.status} /></td><td>{finding.evidence_count}</td><td><div className="flex flex-wrap gap-2"><Link href={`/findings/${finding.id}`} className="text-[#2563EB]">View</Link><Link href="/retests" className="text-[#2563EB]">Retest</Link></div></td></tr>)}</tbody></table></div></CardContent></Card>; }

export function ApprovalQueue({ approvals, scanId }: { approvals?: ScanProcessPayload['approvals']; scanId?: string }) { const { token } = useAuth(); const queryClient = useQueryClient(); const decision = useMutation({ mutationFn: ({ id, value }: { id: string; value: 'approved' | 'rejected' | 'more_information' }) => api.decideApproval(id, value, value === 'approved' ? 'Approved from scan process queue.' : value === 'rejected' ? 'Rejected from scan process queue.' : 'More information requested from scan process queue.', token), onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['scan-process', scanId] }), queryClient.invalidateQueries({ queryKey: ['scan', scanId] }), queryClient.invalidateQueries({ queryKey: ['scan-results', scanId] }), queryClient.invalidateQueries({ queryKey: ['findings'] }), queryClient.invalidateQueries({ queryKey: ['ai-agent-tasks', scanId] })]); toast.success('Approval decision saved'); }, onError: (error) => toast.error(error instanceof Error ? error.message : 'Unable to save approval decision') }); return <Card><CardHeader><h2 className="font-semibold">Approval Queue</h2></CardHeader><CardContent><div className="space-y-3">{approvals?.length ? approvals.map((approval) => <div key={approval.id} className="rounded-xl border border-[#E2E8F0] p-3 text-sm"><div className="flex items-center justify-between"><p className="font-semibold text-[#0F172A]">{approval.action}</p><StatusBadge value={approval.status} /></div><p className="mt-1 text-[#64748B]">Risk: {approval.risk_level}. {approval.reason}</p><div className="mt-3 flex flex-wrap gap-2"><Button disabled={approval.status !== 'pending' || decision.isPending} variant="secondary" onClick={() => decision.mutate({ id: approval.id, value: 'approved' })}>Approve</Button><Button disabled={approval.status !== 'pending' || decision.isPending} variant="outline" onClick={() => decision.mutate({ id: approval.id, value: 'rejected' })}>Reject</Button><Button disabled={approval.status !== 'pending' || decision.isPending} variant="outline" onClick={() => decision.mutate({ id: approval.id, value: 'more_information' })}>Request More Information</Button></div></div>) : <p className="text-sm text-[#64748B]">No pending scan-related approvals.</p>}</div></CardContent></Card>; }

export function NextActionsPanel({ actions }: { actions?: string[] }) { return <Card><CardHeader><h2 className="font-semibold">Next Actions</h2></CardHeader><CardContent><div className="space-y-2">{(actions ?? []).map((action) => <div key={action} className="rounded-xl border border-[#E2E8F0] p-3 text-sm text-[#0F172A]">{action}</div>)}</div></CardContent></Card>; }

export function SeverityDonut({ counts }: { counts: Record<string, number> }) { const colors: Record<string, string> = { critical: '#DC2626', high: '#B91C1C', medium: '#F59E0B', low: '#2563EB', informational: '#64748B' }; const data = Object.entries(counts).map(([name, value]) => ({ name, value, color: colors[name] ?? '#64748B' })); const total = data.reduce((sum, item) => sum + item.value, 0); return <Card><CardHeader><h2 className="font-semibold">Findings Severity</h2></CardHeader><CardContent><p className="sr-only">Severity summary total {total}: {data.map((item) => `${item.name} ${item.value}`).join(', ')}</p><div className="relative h-60"><ResponsiveContainer><PieChart><Pie data={data} dataKey="value" innerRadius={62} outerRadius={90}>{data.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="absolute inset-0 grid place-items-center"><div className="text-center"><p className="text-3xl font-bold text-[#0F172A]">{total}</p><p className="text-xs text-[#64748B]">Total</p></div></div></div></CardContent></Card>; }

export function ScanControls({ status, onPause, onResume, onCancel, onEmergencyStop }: { status?: string; onPause: () => void; onResume: () => void; onCancel: () => void; onEmergencyStop: (text: string) => void }) { const [open, setOpen] = useState(false); const [text, setText] = useState(''); return <div className="flex flex-wrap gap-2">{status === 'running' ? <Button variant="outline" onClick={onPause}><Pause className="h-4 w-4" /> Pause Scan</Button> : null}{status === 'paused' ? <Button variant="outline" onClick={onResume}><Play className="h-4 w-4" /> Resume Scan</Button> : null}{status !== 'completed' && status !== 'cancelled' ? <Button variant="outline" onClick={onCancel}><Square className="h-4 w-4" /> Cancel Scan</Button> : null}{status !== 'completed' ? <Button variant="danger" onClick={() => setOpen(true)}><AlertTriangle className="h-4 w-4" /> Emergency Stop</Button> : null}{open ? <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-lg font-bold text-[#0F172A]">Emergency Stop</h2><button onClick={() => setOpen(false)}><XCircle className="h-5 w-5" /></button></div><p className="mt-3 text-sm text-[#64748B]">Type <strong>STOP SCAN</strong> to immediately stop all related workers and automation tasks.</p><input value={text} onChange={(event) => setText(event.target.value)} className="mt-4 w-full rounded-lg border border-[#E2E8F0] px-3 py-2" /><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button variant="danger" disabled={text !== 'STOP SCAN'} onClick={() => { onEmergencyStop(text); setOpen(false); }}>Emergency Stop</Button></div></div></div> : null}</div>; }

function SelectorGrid({ items, value, onChange, columns = 'md:grid-cols-3' }: { items: Array<{ id: string; title: string; text: string }>; value: string; onChange: (value: string) => void; columns?: string }) { return <div className={`grid gap-4 ${columns}`}>{items.map((item) => <button key={item.id} onClick={() => onChange(item.id)} className={`rounded-2xl border p-5 text-left transition ${value === item.id ? 'border-[#E51C2A] bg-red-50' : 'border-[#E2E8F0] bg-white hover:border-[#E51C2A]/50'}`}><h3 className="font-semibold text-[#0F172A]">{item.title}</h3><p className="mt-2 text-sm leading-6 text-[#64748B]">{item.text}</p></button>)}</div>; }
function Tab({ label, active = false }: { label: string; active?: boolean }) { return <span className={`rounded-full border px-3 py-1 ${active ? 'border-[#E51C2A] bg-red-50 text-[#B91C1C]' : 'border-[#E2E8F0] text-[#64748B]'}`}>{label}</span>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-3 border-b border-slate-100 pb-2"><span className="text-[#64748B]">{label}</span><strong className="text-right text-[#0F172A]">{value}</strong></div>; }
function InfoDark({ label, value, href }: { label: string; value: string; href?: string }) { const content = <><p className="text-xs uppercase tracking-wide text-blue-100">{label}</p><p className="mt-1 break-all font-semibold text-white">{value}</p></>; return <div>{href ? <Link href={href}>{content}</Link> : content}</div>; }
function isSelectableAsset(asset: Asset) { return asset.approval_status === 'approved' && asset.scope_status === 'in_scope' && asset.environment !== 'inactive'; }
function disabledAssetReason(asset: Asset) { if (asset.approval_status !== 'approved') return 'Asset is not approved.'; if (asset.scope_status !== 'in_scope') return 'Asset is outside authorized scope.'; if (asset.environment === 'inactive') return 'Asset is not active.'; return ''; }
