'use client';

import { useState } from 'react';
import { AgentRiskBadge, AgentStatusBadge, AgentTypeBadge } from '@/components/ai-agents/agent-badges';
import type { AIAgent, AIAgentAuditEvent, AIAgentEvidence, AIAgentMessage, AIAgentRecommendation, AIAgentSafetyControl, AIAgentTask } from '@/types/ai-agent';

const tabs = ['Overview', 'Tasks', 'Recommendations', 'Evidence Used', 'Execution Trace', 'Safety Controls', 'Audit History', 'Configuration'];

export function AgentDetailHeader({ agent }: { agent: AIAgent }) {
  return <div className="rounded-2xl border border-[#223044] bg-[#0D1928] p-6"><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><h1 className="text-3xl font-bold text-white">{agent.name}</h1><p className="mt-2 max-w-3xl text-[#94A3B8]">{agent.description}</p></div><div className="flex flex-wrap gap-2"><AgentTypeBadge type={agent.type} /><AgentStatusBadge status={agent.status} /><AgentRiskBadge risk={agent.riskLevel} /></div></div></div>;
}

export function AgentDetailTabs({ agent, tasks, recommendations, evidence, messages, controls, auditEvents, canConfigure }: { agent: AIAgent; tasks: AIAgentTask[]; recommendations: AIAgentRecommendation[]; evidence: AIAgentEvidence[]; messages: AIAgentMessage[]; controls: AIAgentSafetyControl[]; auditEvents: AIAgentAuditEvent[]; canConfigure: boolean }) {
  const [active, setActive] = useState('Overview');
  return <section className="rounded-2xl border border-[#223044] bg-[#0D1928]"><div className="flex gap-2 overflow-x-auto border-b border-[#223044] p-3">{tabs.map((tab) => <button key={tab} onClick={() => setActive(tab)} className={`whitespace-nowrap rounded-xl px-3 py-2 text-sm font-semibold ${active === tab ? 'bg-[#E51C2A] text-white' : 'text-[#94A3B8] hover:bg-[#111E2E]'}`}>{tab}</button>)}</div><div className="p-5">{active === 'Overview' ? <Grid items={{ 'Automation name': agent.name, Type: agent.type, Description: agent.description, Status: agent.status, 'Current engagement': agent.engagement ?? 'None', 'Current task': agent.currentTask, 'Risk level': agent.riskLevel, Model: agent.model, 'Prompt version': agent.promptVersion, 'Policy version': agent.policyVersion, 'Last heartbeat': agent.lastHeartbeat, 'Last activity': agent.lastActivity }} /> : null}{active === 'Tasks' ? <AgentTaskTable tasks={tasks} /> : null}{active === 'Recommendations' ? <List rows={recommendations.map((item) => [item.id, item.title, item.reason, `${item.confidence}%`, item.reviewStatus])} /> : null}{active === 'Evidence Used' ? <AgentEvidencePanel evidence={evidence} /> : null}{active === 'Execution Trace' ? <AgentCommunicationTable messages={messages} /> : null}{active === 'Safety Controls' ? <AgentSafetyPanel controls={controls} /> : null}{active === 'Audit History' ? <AgentAuditTimeline events={auditEvents} /> : null}{active === 'Configuration' ? <div className="text-[#CBD5E1]">{canConfigure ? 'Configuration is available for administrators. Mandatory safety controls cannot be disabled.' : 'Administration-only configuration.'}</div> : null}</div></section>;
}

function Grid({ items }: { items: Record<string, string> }) { return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{Object.entries(items).map(([key, value]) => <div key={key} className="rounded-xl border border-[#223044] bg-[#111E2E] p-3"><p className="text-xs uppercase tracking-wide text-[#64748B]">{key}</p><p className="mt-1 text-sm font-semibold text-white">{value}</p></div>)}</div>; }
function List({ rows }: { rows: string[][] }) { return <div className="space-y-3">{rows.map((row) => <div key={row.join('-')} className="rounded-xl border border-[#223044] bg-[#111E2E] p-3 text-sm text-[#CBD5E1]">{row.map((cell) => <p key={cell}>{cell}</p>)}</div>)}</div>; }
export function AgentTaskTable({ tasks }: { tasks: AIAgentTask[] }) { return <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="text-[#64748B]"><tr>{['Task ID', 'Objective', 'Engagement', 'Target', 'Risk', 'Status', 'Control', 'Started', 'Duration', 'Result'].map((h) => <th key={h} className="px-3 py-2">{h}</th>)}</tr></thead><tbody>{tasks.map((task) => <tr key={task.id} className="border-t border-[#223044] text-[#CBD5E1]"><td className="px-3 py-2">{task.id}</td><td className="px-3 py-2">{task.objective}</td><td className="px-3 py-2">{task.engagement}</td><td className="px-3 py-2">{task.target}</td><td className="px-3 py-2">{task.risk}</td><td className="px-3 py-2">{task.status}</td><td className="px-3 py-2">{task.controlStatus}</td><td className="px-3 py-2">{task.started}</td><td className="px-3 py-2">{task.duration}</td><td className="px-3 py-2">{task.result}</td></tr>)}</tbody></table></div>; }
export function AgentEvidencePanel({ evidence }: { evidence: AIAgentEvidence[] }) { return <List rows={evidence.map((item) => [item.id, item.findingId, item.type, item.source, item.captureTime, item.hash, item.redactionStatus, item.preview])} />; }
export function AgentCommunicationTable({ messages }: { messages: AIAgentMessage[] }) { return <List rows={messages.map((item) => [item.sender, item.receiver, item.taskId, item.messageType, item.timestamp, item.validationStatus])} />; }
export function AgentSafetyPanel({ controls }: { controls: AIAgentSafetyControl[] }) { return <List rows={controls.map((item) => [item.name, item.status, item.policyVersion, item.recommendedAction])} />; }
export function AgentAuditTimeline({ events }: { events: AIAgentAuditEvent[] }) { return <List rows={events.map((item) => [item.timestamp, item.actor, item.action, item.details])} />; }
