'use client';

import { useMutation } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { toast } from 'sonner';
import { aiAgentsApi } from '@/api/ai-agents';

const schema = z.object({ name: z.string().min(3), type: z.string(), description: z.string().min(8), purpose: z.string().min(8), provider: z.string(), model: z.string(), promptVersion: z.string(), policyVersion: z.string(), allowedTools: z.string(), allowedTasks: z.string(), maxRisk: z.string(), controlLevel: z.string(), timeout: z.coerce.number().min(10), retryLimit: z.coerce.number().min(0), memoryPolicy: z.string(), status: z.string() });
type FormValues = z.infer<typeof schema>;

export function CustomAgentForm() {
  const form = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: { name: '', type: 'Planner', description: '', purpose: '', provider: 'Ollama', model: 'qwen3-coder:30b-64k', promptVersion: 'pv-2025.04', policyVersion: 'ASI-2025.07', allowedTools: 'Safe platform tools only', allowedTasks: 'Planning, validation, remediation, report writing', maxRisk: 'Medium', controlLevel: 'Human review for high risk', timeout: 90, retryLimit: 1, memoryPolicy: 'Engagement-scoped only', status: 'Idle' } });
  const create = useMutation({ mutationFn: (values: FormValues) => aiAgentsApi.createAgent({ name: values.name, type: values.type as never, description: values.description, purpose: values.purpose, provider: values.provider, model: values.model, promptVersion: values.promptVersion, policyVersion: values.policyVersion, status: values.status as never, currentTask: 'No active task', riskLevel: values.maxRisk as never, lastActivity: 'just now', lastHeartbeat: 'just now' }), onSuccess: () => toast.success('Automation profile created'), onError: (error) => toast.error(error instanceof Error ? error.message : 'Unable to create automation profile') });
  return <form onSubmit={form.handleSubmit((values) => create.mutate(values))} className="rounded-2xl border border-[#223044] bg-[#0D1928] p-6"><div className="grid gap-4 md:grid-cols-2">{['name', 'description', 'purpose', 'model', 'promptVersion', 'policyVersion', 'allowedTools', 'allowedTasks', 'controlLevel', 'memoryPolicy'].map((field) => <label key={field} className="text-sm font-semibold text-[#CBD5E1]"><span>{field}</span><input {...form.register(field as keyof FormValues)} className="mt-2 w-full rounded-xl border border-[#223044] bg-[#091522] px-3 py-2 text-white" /></label>)}<Select label="type" register={form.register('type')} options={['Planner', 'Discovery', 'Scanner', 'Validator', 'Advisor', 'Writer', 'Context']} /><Select label="provider" register={form.register('provider')} options={['Ollama', 'OpenAI-compatible']} /><Select label="maxRisk" register={form.register('maxRisk')} options={['Low', 'Medium', 'High', 'Critical']} /><Select label="status" register={form.register('status')} options={['Idle', 'Paused']} /><label className="text-sm font-semibold text-[#CBD5E1]"><span>timeout</span><input type="number" {...form.register('timeout')} className="mt-2 w-full rounded-xl border border-[#223044] bg-[#091522] px-3 py-2 text-white" /></label><label className="text-sm font-semibold text-[#CBD5E1]"><span>retryLimit</span><input type="number" {...form.register('retryLimit')} className="mt-2 w-full rounded-xl border border-[#223044] bg-[#091522] px-3 py-2 text-white" /></label></div><div className="mt-5 rounded-xl border border-green-500/30 bg-green-500/10 p-3 text-sm text-green-300">Mandatory automation safety controls are enforced and cannot be disabled. Provider secret keys are never exposed.</div><button className="mt-6 rounded-xl bg-[#E51C2A] px-4 py-2 text-sm font-semibold text-white">Create Automation Profile</button></form>;
}

function Select({ label, register, options }: { label: string; register: Record<string, unknown>; options: string[] }) { return <label className="text-sm font-semibold text-[#CBD5E1]"><span>{label}</span><select {...register} className="mt-2 w-full rounded-xl border border-[#223044] bg-[#091522] px-3 py-2 text-white">{options.map((item) => <option key={item}>{item}</option>)}</select></label>; }
